### ISSUE TITLE
TODO: Documentation

### ISSUE THREAD

**Issue by xnuk** [xnuk/crawl-it#1]
- [x] add more comments
- [x] add How to Use™ guide & example
- [x] explain the syntax and what it works
